name: Api RestAssured CI Pipeline

on:
  push:
    branches:
      - master

  schedule:
    - cron: '0 0 * * 1'  # runs every Sunday at 7 30 PM IST

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps: # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up JDK 17 (adjust the version as needed)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Options: 'temurin', 'zulu', 'adopt'
          java-version: 11

      # Set up Maven with Java 11 (adjust the version as needed)
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      # Compile project
      - name: Build with Maven
        run: mvn clean compile

      # Run tests
      - name: Run tests
        run: mvn clean test

      # Upload test report
      - name: Upload test report artifact
        uses: actions/upload-artifact@v3
        if: ${{always()}}
        with:
          name: test-report
          path: target/surefire-reports/
          if-no-files-found: 'error'





